spring:
  config:
    activate:
      on-profile: local
filepath:
  blacklist: ./src/main/resources/customer_blacklist.csv

---
spring:
  config:
    activate:
      on-profile: file

filepath:
  voucher: ./src/main/resources/voucher_list.csv
  blacklist: ./src/main/resources/customer_blacklist.csv
